# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_auto_20170610_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.CharField(db_column='bill_id', default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='blurb',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bill',
            name='chamber',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bill',
            name='leg_id',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='leg_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='sponsor',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
