# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0005_auto_20170610_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='leg_id',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='leg_name',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
