SUBJECTS = {
'Agriculture and Food': False,
'Animal Rights and Wildlife Issues': False,
'Arts and Humanities': False,
'Budget, Spending, and Taxes': False,
'Business and Consumers': False,
'Campaign Finance and Election Issues': False,
'Civil Liberties and Civil Rights': False,
'Commerce': False,
'Crime': False,
'Drugs': False,
'Education': False,
'Energy': False,
'Environmental': False,
'Executive Branch': False,
'Family and Children Issues': False,
'Federal, State, and Local Relations': False,
'Gambling and Gaming': False,
'Government Reform': False,
'Guns': False,
'Health': False,
'Housing and Property': False,
'Immigration': False,
'Indigenous Peoples': False,
'Insurance': False,
'Judiciary': False,
'Labor and Employment': False,
'Legal Issues': False,
'Legislative Affairs': False,
'Military': False,
'Municipal and County Issues': False,
'Nominations': False,
'Other': False,
'Public Services': False,
'Recreation': False,
'Reproductive Issues': False,
'Resolutions': False,
'Science and Medical Research': False,
'Senior Issues': False,
'Sexual Orientation and Gender Issues': False,
'Social Issues': False,
'State Agencies': False,
'Technology and Communication': False,
'Trade': False,
'Transportation': False,
'Welfare and Poverty': False
}
