import axios from 'axios';
import { HOST_URL } from './host_util';

export const saveSubjects = subjects => {
  return axios({
    method: 'PATCH',
    url: `${HOST_URL}/api/users/subjects`,
    data: subjects
  });
};

export const SUBJECTS = {
  'Agriculture and Food': false,
  'Animal Rights and Wildlife Issues': false,
  'Arts and Humanities': false,
  'Budget, Spending, and Taxes': false,
  'Business and Consumers': false,
  'Campaign Finance and Election Issues': false,
  'Civil Liberties and Civil Rights': false,
  'Commerce': false,
  'Crime': false,
  'Drugs': false,
  'Education': false,
  'Energy': false,
  'Environmental': false,
  'Executive Branch': false,
  'Family and Children Issues': false,
  'Federal, State, and Local Relations': false,
  'Gambling and Gaming': false,
  'Government Reform': false,
  'Guns': false,
  'Health': false,
  'Housing and Property': false,
  'Immigration': false,
  'Indigenous Peoples': false,
  'Insurance': false,
  'Judiciary': false,
  'Labor and Employment': false,
  'Legal Issues': false,
  'Legislative Affairs': false,
  'Military': false,
  'Municipal and County Issues': false,
  'Nominations': false,
  'Other': false,
  'Public Services': false,
  'Recreation': false,
  'Reproductive Issues': false,
  'Resolutions': false,
  'Science and Medical Research': false,
  'Senior Issues': false,
  'Sexual Orientation and Gender Issues': false,
  'Social Issues': false,
  'State Agencies': false,
  'Technology and Communication': false,
  'Trade': false,
  'Transportation': false,
  'Welfare and Poverty': false
};

export const SUBJECT_IMAGES = {
  'Agriculture and Food': require("../components/subjects/images/AgricultureandFood.jpg"),
  'Animal Rights and Wildlife Issues': require("../components/subjects/images/AnimalRights.jpg"),
  'Arts and Humanities': require("../components/subjects/images/Arts.jpg"),
  'Budget, Spending, and Taxes': require("../components/subjects/images/Budget.jpg"),
  'Business and Consumers': require("../components/subjects/images/Business.jpg"),
  'Campaign Finance and Election Issues': require("../components/subjects/images/ElectionIssues.jpg"),
  'Civil Liberties and Civil Rights': require("../components/subjects/images/Civilrights.jpg"),
  'Commerce': require("../components/subjects/images/Commerce.jpg"),
  'Crime': require("../components/subjects/images/Crime.jpg"),
  'Drugs': require("../components/subjects/images/Drugs.jpg"),
  'Education': require("../components/subjects/images/Education.jpg"),
  'Energy': require("../components/subjects/images/Energy.jpg"),
  'Environmental': require("../components/subjects/images/Environment.jpg"),
  'Executive Branch': require("../components/subjects/images/Executive.jpg"),
  'Family and Children Issues': require("../components/subjects/images/Family.jpg"),
  'Federal, State, and Local Relations': require("../components/subjects/images/Social2.jpg"),
  'Gambling and Gaming': require("../components/subjects/images/Gambling.jpg"),
  'Government Reform': require("../components/subjects/images/Governmentreform.jpg"),
  'Guns': require("../components/subjects/images/Guns.jpg"),
  'Health': require("../components/subjects/images/Health.jpg"),
  'Housing and Property': require("../components/subjects/images/Housing.jpg"),
  'Immigration': require("../components/subjects/images/Immigration.jpg"),
  'Indigenous Peoples': require("../components/subjects/images/IndigenousPeoples.jpg"),
  'Insurance': require("../components/subjects/images/Insurance.jpg"),
  'Judiciary': require("../components/subjects/images/Judiciary.jpg"),
  'Labor and Employment': require("../components/subjects/images/Labor.jpg"),
  'Legal Issues': require("../components/subjects/images/Legal.jpg"),
  'Legislative Affairs': require("../components/subjects/images/LegislativeAffairs.jpg"),
  'Military': require("../components/subjects/images/Military.jpg"),
  'Municipal and County Issues': require("../components/subjects/images/Municipal.jpg"),
  'Nominations': require("../components/subjects/images/Nominations.jpg"),
  'Other': require("../components/subjects/images/Other.jpg"),
  'Public Services': require("../components/subjects/images/PublicService.jpg"),
  'Recreation': require("../components/subjects/images/Recreation.jpg"),
  'Reproductive Issues': require("../components/subjects/images/Reproductive.jpg"),
  'Resolutions': require("../components/subjects/images/Resolutions.jpg"),
  'Science and Medical Research': require("../components/subjects/images/Science.jpg"),
  'Senior Issues': require("../components/subjects/images/Senior.jpg"),
  'Sexual Orientation and Gender Issues': require("../components/subjects/images/SexualOrientation.jpg"),
  'Social Issues': require("../components/subjects/images/Social.jpg"),
  'State Agencies': require("../components/subjects/images/StateAgency.jpg"),
  'Technology and Communication': require("../components/subjects/images/Technology.jpg"),
  'Trade': require("../components/subjects/images/Trade.jpg"),
  'Transportation': require("../components/subjects/images/PublicTransit.jpg"),
  'Welfare and Poverty': require("../components/subjects/images/Welfare.jpg")
};
