# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_auto_20170610_2356'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bills',
        ),
        migrations.AddField(
            model_name='user',
            name='bills',
            field=models.ManyToManyField(blank=True, to='bills.Bill'),
        ),
    ]
