# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170610_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fb_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
