# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 06:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170608_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='representatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=[], size=None),
        ),
    ]
