# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 01:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170609_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='representatives',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, null=True), blank=True, default=[], size=None),
        ),
    ]
